### ISSUE TITLE
 Fatal error: Class 'Unicodeveloper\Identify\IdentifyServiceProvider' not found

### ISSUE THREAD

**Issue by alehtrambacheuski** [unicodeveloper/laravel-identify#1]
laravel v5.2.10
$ php artisan vendor:publish --provider="Unicodeveloper\Identify\IdentifyServiceProvider"

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Class 'Unicodeveloper\Identify\IdentifyServiceProvider' not found

**Comment by unicodeveloper** [comment]
Fixed Now. Upgrade to 1.1.0 or 1.1.1. Thanks for the quick notice @alehtrambacheuski

**Comment by unicodeveloper** [comment]
Please could you try it again? @alehtrambacheuski

**Comment by alehtrambacheuski** [comment]
Perfect thank you!
