### ISSUE TITLE
Tests are needed for this project

### ISSUE THREAD

**Issue by unicodeveloper** [unicodeveloper/laravel-identify#3]

**Comment by perfectmak** [comment]
I just came across this package and I must say it is quite a useful package for laravel.
I would like to write tests for it.
I'll make a pull request soon, but in the meantime, I'll might be asking some questions about the best way to go about writing tests for this package.

**Comment by unicodeveloper** [comment]
That would be awesome @perfectmak . Let me know whenever you are ready & I'll be ready to guide you on writing tests for it too.

**Comment by perfectmak** [comment]
Okay, great.
Thanks.

I'm ready now. I had to upgrade my php to php7 😊
I've forked the repo.
So I'm guessing the only entity that requires unit testing is the Identity
Class.
I'll attempt creating some preliminary unit tests and send you a pull
request, and then we can continue from there.
Any other pointers will be appreciated. Thanks.

On Mon, Apr 18, 2016 at 7:38 PM, Prosper Otemuyiwa <notifications@github.com
> wrote:

> That would be awesome @perfectmak <https://github.com/perfectmak> . Let
> me know whenever you are ready & I'll be ready to guide you on writing
> tests for it too.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/unicodeveloper/laravel-identify/issues/3#issuecomment-211518796>
>



-- 
Makanju Perfect

**Comment by unicodeveloper** [comment]
That's great. Please send in a PR and we can continue from there 😊
