### ISSUE TITLE
failing to install laravel 5.1

### ISSUE THREAD

**Issue by josina08** [unicodeveloper/laravel-identify#5]
Problem 1
    - illuminate/support v5.2.25 requires illuminate/contracts 5.3.* -> satisfiable by illuminate/contracts[5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - Conclusion: remove laravel/framework v5.1.35
    - Conclusion: don't install laravel/framework v5.1.35
    - Conclusion: don't install laravel/framework v5.1.34
    - Conclusion: don't install laravel/framework v5.1.33
    - Conclusion: don't install laravel/framework v5.1.32
    - Conclusion: don't install laravel/framework v5.1.31
    - Conclusion: don't install laravel/framework v5.1.30
    - Conclusion: don't install laravel/framework v5.1.29
    - Conclusion: don't install laravel/framework v5.1.28
    - Conclusion: don't install laravel/framework v5.1.27
    - Conclusion: don't install laravel/framework v5.1.26
    - Conclusion: don't install laravel/framework v5.1.25
    - Conclusion: don't install laravel/framework v5.1.24
    - Conclusion: don't install laravel/framework v5.1.23
    - Conclusion: don't install laravel/framework v5.1.22
    - Conclusion: don't install laravel/framework v5.1.21
    - Conclusion: don't install laravel/framework v5.1.20
    - Conclusion: don't install laravel/framework v5.1.19
    - Conclusion: don't install laravel/framework v5.1.18
    - Conclusion: don't install laravel/framework v5.1.17
    - Conclusion: don't install laravel/framework v5.1.16
    - Conclusion: don't install laravel/framework v5.1.15
    - Conclusion: don't install laravel/framework v5.1.14
    - Conclusion: don't install laravel/framework v5.1.13
    - Conclusion: don't install laravel/framework v5.1.12
    - Conclusion: don't install laravel/framework v5.1.11
    - Conclusion: don't install laravel/framework v5.1.10
    - Conclusion: don't install laravel/framework v5.1.9
    - Conclusion: don't install laravel/framework v5.1.8
    - Conclusion: don't install laravel/framework v5.1.7
    - Conclusion: don't install laravel/framework v5.1.6
    - Conclusion: don't install laravel/framework v5.1.5
    - Conclusion: don't install laravel/framework v5.1.4
    - Conclusion: don't install laravel/framework v5.1.3
    - Conclusion: don't install laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.1
    - unicodeveloper/laravel-identify 1.1.0 requires illuminate/support 5.2.* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.6, v5.2.7].
    - unicodeveloper/laravel-identify 1.1.1 requires illuminate/support 5.2.* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.1.0
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.1.0
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20, v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9].
    - Installation request for unicodeveloper/laravel-identify 1.1.* -> satisfiable by unicodeveloper/laravel-identify[1.1.0, 1.1.1].

**Comment by unicodeveloper** [comment]
Sorry about that, I used Illuminate/support 5.2.* meaning you might have to upgrade your app to Laravel 5.2. I built this on 5.2 @josina08

**Comment by josina08** [comment]
thanks...upgrading to 5.2
