### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by victorybiz** [unicodeveloper/laravel-identify#8]
Not working with laravel 5.5....

Problem 1
    - Conclusion: remove laravel/framework v5.5.4
    - Conclusion: don't install laravel/framework v5.5.4
    - unicodeveloper/laravel-identify 1.1.0 requires illuminate/support 5.2.* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - unicodeveloper/laravel-identify 1.1.1 requires illuminate/support 5.2.* -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.5.4
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.5.4
    - Installation request for laravel/framework (locked at v5.5.4, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.4].
    - Installation request for unicodeveloper/laravel-identify ^1.1 -> satisfiable by unicodeveloper/laravel-identify[1.1.0, 1.1.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by unicodeveloper** [comment]
@victorybiz It's now working on Laravel 5.5. Check https://github.com/unicodeveloper/laravel-identify/releases/tag/1.4.0
